Repository Inspire-Poli-USP/Inspire-OpenLung, pull requests merged in 2020-04, with the labels that each got.

#53 adicionando botao de contribuicao
  .github/FUNDING.yml
Labels: documentation

#61 adicionando novo link de funding
  .github/FUNDING.yml
Labels: Documentação

#69 Substituindo subemetendo ~> submetendo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentação

#68 Teste de documentação com CI
  .gitignore
  .travis.yml
  2D laser cut/v5/README.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Paginas_wiki/Wiki_Entenda_o_Problema.md
  Paginas_wiki/Wiki_FAQ.md
  Paginas_wiki/Wiki_HOME.md
  Paginas_wiki/Wiki_Regulamentação.md
  Paginas_wiki/Wiki_Sistema_de_Testes.md
  Paginas_wiki/Wiki_Válvula_PEEP.md
  Principios_e_abordagem.md
  README.md
  package.json
  yarn.lock
Labels: Documentação, software
